lib: [
  "_build/install/default/lib/ppx_testify/META"
  "_build/install/default/lib/ppx_testify/dune-package"
  "_build/install/default/lib/ppx_testify/opam"
  "_build/install/default/lib/ppx_testify/ppx_testify.a"
  "_build/install/default/lib/ppx_testify/ppx_testify.cma"
  "_build/install/default/lib/ppx_testify/ppx_testify.cmi"
  "_build/install/default/lib/ppx_testify/ppx_testify.cmt"
  "_build/install/default/lib/ppx_testify/ppx_testify.cmx"
  "_build/install/default/lib/ppx_testify/ppx_testify.cmxa"
  "_build/install/default/lib/ppx_testify/ppx_testify.cmxs"
  "_build/install/default/lib/ppx_testify/ppx_testify.ml"
]
libexec: [
  "_build/install/default/lib/ppx_testify/ppx.exe"
]
doc: [
  "_build/install/default/doc/ppx_testify/LICENSE"
  "_build/install/default/doc/ppx_testify/README.md"
]
